#################################################
# General Settings
#nsible_python_interpreter: /usr/bin/python3
admin_user:           admin             # Administration user for all hosts
admin_password:       admin             # Admin user password

#################################################
# Mongodb Settings
mongo_user:           mongodb         # MongoDB username
mongo_db:             mikasadb        # MongoDB database name

#################################################
# Wildfly Settings
http_port:            8090            # JBoss port for http connections
https_port:           8443            # JBoss port for https connections
wildfly_user:         wildfly
wildfly_basedir:      /opt
wildfly_home:         /opt/wildfly
wildfly_version:      11.0.0.Final
wildfly_admin:        admin         # Management console admin user

#################################################
# Gradle Settings
dev_tools_dir:        /usr/lib
gradle_version:       4.2
