#################################################
# General Settings
#ansible_python_interpreter: /usr/bin/python3

#################################################
# Mongodb Settings
mongo_user:           mongodb         # MongoDB username
mongo_password:       mongodb         # MongoDB password
mongo_db:             mikasadb        # MongoDB database name
mongo_collections:
  - users
  - plans
  - activities


#################################################
# Wildfly Settings
http_port:            8090            # JBoss port for http connections
https_port:           8443            # JBoss port for https connections
wildfly_user:         wildfly
wildfly_basedir:      /opt
wildfly_home:         /opt/wildfly
wildfly_version:      11.0.0.Final
wildfly_admin:        admin         # Management console admin user
wildfly_password:     admin         # Management console admin password

dev_tools_dir:        /usr/lib
gradle_version:       4.2

#################################################
# OpenLDAP Settings
ldap_auth:
  server_uri: ldap://localhost:389
  bind_dn: cn=admin,dc=golili,dc=net
  bind_pw: secret
ldap_username:        admin
ldap_password:        secret
ldap_basedn:          dc=golili,dc=net
ldap_users:
  admin:
    cn: System Administrator
    givenname: System
    sn: Administrator
    mail: admin@golili.net
    userpassword: admin
  lnovo:
    cn: Luis Novo
    givenname: Luis
    sn: Novo
    mail: lnovo@golili.net
    userpassword: alibaba
  erodriguez:
    cn: Elena Rodriguez
    givenname: Elena
    sn: Rodriguez
    mail: erodriguez@golili.net
    userpassword: alibaba
  aperez:
    cn: Alberto Perez
    givenname: Alberto
    sn: Perez
    mail: aperez@golili.net
    userpassword: alibaba

ldap_groups:
  - name: administrators
    members:
      - admin
  - name: developers
    members:
      - lnovo
      - erodriguez
      - aperez
