#################################################
# General Settings
ansible_python_interpreter: /usr/bin/python3
#hostname: mikasaweb.golili.net
#remote_user: ubuntu
filespath: ../../src/main/db

#################################################
# Mysql Settings
ddbbname: mikasadb
ddbbuser: mikasadb
ddbbpassword: mikasadb

#################################################
# bennojoy galaxy mysql role
mysql_root_db_pass: saupw
mysql_repl_role: none
#mysql_db:
#- name: mikasadb
#  replicate: no
#mysql_users:
#- name: mikasadb
#  pass: mikasadb
#  priv: "*.*:ALL"

#################################################
# OpenLDAP Settings
# admin_user: admin
admin_password: secret
ddbb_path: /var/lib/ldap/golili
base_dn: dc=golili,dc=net
ldap_host: localhost
ldap_port: 389

jdk_basedir:          /usr/lib/java   # JDK Install dir
jdk_version:          jdk1.8.0_131

jboss_home:           /opt            # JBoss install dir
http_port:            8090            # JBoss port for http connections
https_port:           8443            # JBoss port for https connections

wildfly_user:         wildfly
wildfly_basedir:      /opt
wildfly_home:         /opt/wildfly
wildfly_version:      10.1.0.Final