package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name="AUTHORITIES"
    ,catalog="tcms"
    , uniqueConstraints = @UniqueConstraint(columnNames={"USERNAME", "AUTHORITY"}) 
)
public class Authorities  implements java.io.Serializable {


     private AuthoritiesId id;
     private Users users;

    public Authorities() {
    }

    public Authorities(AuthoritiesId id, Users users) {
       this.id = id;
       this.users = users;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="username", column=@Column(name="USERNAME", nullable=false, length=10) ), 
        @AttributeOverride(name="authority", column=@Column(name="AUTHORITY", nullable=false, length=20) ) } )
    public AuthoritiesId getId() {
        return this.id;
    }
    
    public void setId(AuthoritiesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERNAME", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


