package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name="CITIES"
    ,catalog="tcms"
)
public class Cities  implements java.io.Serializable {


     private int id;
     private Provinces provinces;
     private String name;

    public Cities() {
    }

	
    public Cities(int id, Provinces provinces) {
        this.id = id;
        this.provinces = provinces;
    }
    public Cities(int id, Provinces provinces, String name) {
       this.id = id;
       this.provinces = provinces;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROVINCE_ID", nullable=false)
    public Provinces getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Provinces provinces) {
        this.provinces = provinces;
    }
    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


