package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="COUNTRIES"
    ,catalog="tcms"
)
public class Countries  implements java.io.Serializable {


     private int id;
     private String code;
     private String name;

    public Countries() {
    }

    public Countries(int id, String code, String name) {
       this.id = id;
       this.code = code;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="CODE", nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="NAME", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


