package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provinces generated by hbm2java
 */
@Entity
@Table(name="PROVINCES"
    ,catalog="tcms"
)
public class Provinces  implements java.io.Serializable {


     private int id;
     private Regions regions;
     private String name;
     private Set<Cities> citieses = new HashSet<Cities>(0);

    public Provinces() {
    }

	
    public Provinces(int id) {
        this.id = id;
    }
    public Provinces(int id, Regions regions, String name, Set<Cities> citieses) {
       this.id = id;
       this.regions = regions;
       this.name = name;
       this.citieses = citieses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REGION_ID")
    public Regions getRegions() {
        return this.regions;
    }
    
    public void setRegions(Regions regions) {
        this.regions = regions;
    }
    
    @Column(name="NAME", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="provinces")
    public Set<Cities> getCitieses() {
        return this.citieses;
    }
    
    public void setCitieses(Set<Cities> citieses) {
        this.citieses = citieses;
    }




}


