package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name="REGIONS"
    ,catalog="tcms"
)
public class Regions  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Provinces> provinceses = new HashSet<Provinces>(0);

    public Regions() {
    }

	
    public Regions(int id) {
        this.id = id;
    }
    public Regions(int id, String name, Set<Provinces> provinceses) {
       this.id = id;
       this.name = name;
       this.provinceses = provinceses;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="regions")
    public Set<Provinces> getProvinceses() {
        return this.provinceses;
    }
    
    public void setProvinceses(Set<Provinces> provinceses) {
        this.provinceses = provinceses;
    }




}


