package net.mikasa.mikasaweb.model;
// Generated Feb 26, 2013 11:34:24 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,catalog="tcms"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String name;
     private String surname;
     private String email;
     private String password;
     private String organization;
     private int enabled;
     private Set<Authorities> authoritieses = new HashSet<Authorities>(0);

    public Users() {
    }

	
    public Users(String username, String name, String surname, String email, String password, String organization, int enabled) {
        this.username = username;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.password = password;
        this.organization = organization;
        this.enabled = enabled;
    }
    public Users(String username, String name, String surname, String email, String password, String organization, int enabled, Set<Authorities> authoritieses) {
       this.username = username;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.password = password;
       this.organization = organization;
       this.enabled = enabled;
       this.authoritieses = authoritieses;
    }
   
     @Id 
    
    @Column(name="USERNAME", unique=true, nullable=false, length=10)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="SURNAME", nullable=false, length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    @Column(name="EMAIL", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="ORGANIZATION", nullable=false, length=100)
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    
    @Column(name="ENABLED", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Authorities> getAuthoritieses() {
        return this.authoritieses;
    }
    
    public void setAuthoritieses(Set<Authorities> authoritieses) {
        this.authoritieses = authoritieses;
    }




}


