---
- name: Get deb package
  apt_repository:
    repo: deb https://download.gocd.org /
    validate_certs: no

- name: Add GPG key
  apt_key:
    url: https://download.gocd.org/GOCD-GPG-KEY.asc
    validate_certs: no

- name: Install gocd agent
  apt:
    name: go-agent
    state: present
    allow_unauthenticated: yes

- name: Transfer agent config
  copy:
    src: go-agent
    dest: /etc/defaults
    owner: root
    group: go
    mode: 0640

- name: Start go-agent service
  service:
    name: "{{item}}"
    state: started
  with_items:
    - go-agent