---
- name: Download and uncompress archive
  unarchive:
    src: "https://services.gradle.org/distributions/gradle-{{gradle_version}}-bin.zip"
    dest: "{{dev_tools_dir}}"
    remote_src: yes
    creates: "{{dev_tools_dir}}/gradle-{{gradle_version}}"

- name: Create symlink to gradle executable
  file:
    src: "{{dev_tools_dir}}/gradle-{{gradle_version}}/bin/gradle"
    dest: /usr/bin/gradle
    state: link
    owner: root
    group: root
    mode: 0755
