---
- hosts: all
  vars_files: 
    - vault.yml
  roles:
    - capitanh.common_ansible_role
    - capitanh.openldap-ansible-role
    - capitanh.mongodb-ansible-role
  tasks:
  - include_tasks: mongodb.yml
