---
- hosts: all
  environment:
    DEBIAN_FRONTEND: noninteractive
    LANGUAGE: en_US.UTF-8
    LC_ALL: en_US.UTF-8

  roles:
    - capitanh.mysql-ansible-role

  tasks:
  - include_tasks: mysql.yml
