# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.box = 'bento/ubuntu-20.04'
  config.vm.network "forwarded_port", host: 27017,guest: 27017  # MongoDB
  config.vm.network "forwarded_port", host: 10389,guest:   389  # OpenLDAP

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'mikasaweb'
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = false
  end
  config.vm.hostname = 'mikasaweb.golili.net'

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = 'site.yml'
    ansible.galaxy_role_file = 'requirements.yml'
    ansible.galaxy_roles_path = '~/.ansible/roles'
    ansible.groups = {
      "mongodb_servers" => ["default"],
      "openldap_servers" => ["default"]
    }    
  end

end
