{_id:1,name:"Álava",region_id:17},
{_id:2,name:"Albacete",region_id:7},
{_id:3,name:"Alicante",region_id:18},
{_id:4,name:"Almería",region_id:1},
{_id:5,name:"Ávila",region_id:6},
{_id:6,name:"Badajoz",region_id:10},
{_id:7,name:"Illes Balears",region_id:4},
{_id:8,name:"Barcelona",region_id:8},
{_id:9,name:"Burgos",region_id:6},
{_id:10,name:"Cáceres",region_id:10},
{_id:11,name:"Cádiz",region_id:1},
{_id:12,name:"Castellón",region_id:18},
{_id:13,name:"Ciudad Real",region_id:7},
{_id:14,name:"Córdoba",region_id:1},
{_id:15,name:"A Coruña",region_id:11},
{_id:16,name:"Cuenca",region_id:7},
{_id:17,name:"Girona",region_id:8},
{_id:18,name:"Granada",region_id:1},
{_id:19,name:"Guadalajara",region_id:7},
{_id:20,name:"Guipúzcoa",region_id:17},
{_id:21,name:"Huelva",region_id:1},
{_id:22,name:"Huesca",region_id:2},
{_id:23,name:"Jaén",region_id:1},
{_id:24,name:"León",region_id:6},
{_id:25,name:"Lleida",region_id:8},
{_id:26,name:"La Rioja",region_id:13},
{_id:27,name:"Lugo",region_id:11},
{_id:28,name:"Madrid",region_id:14},
{_id:29,name:"Málaga",region_id:1},
{_id:30,name:"Murcia",region_id:15},
{_id:31,name:"Navarra",region_id:16},
{_id:32,name:"Ourense",region_id:11},
{_id:33,name:"Asturias",region_id:3},
{_id:34,name:"Palencia",region_id:6},
{_id:35,name:"Las Palmas",region_id:12},
{_id:36,name:"Pontevedra",region_id:11},
{_id:37,name:"Salamanca",region_id:6},
{_id:38,name:"Santa Cruz de Tenerife",region_id:12},
{_id:39,name:"Cantabria",region_id:5},
{_id:40,name:"Segovia",region_id:6},
{_id:41,name:"Sevilla",region_id:1},
{_id:42,name:"Soria",region_id:6},
{_id:43,name:"Tarragona",region_id:8},
{_id:44,name:"Teruel",region_id:2},
{_id:45,name:"Toledo",region_id:7},
{_id:46,name:"Valencia",region_id:18},
{_id:47,name:"Valladolid",region_id:6},
{_id:48,name:"Vizcaya",region_id:17},
{_id:49,name:"Zamora",region_id:6},
{_id:50,name:"Zaragoza",region_id:2},
{_id:51,name:"Ceuta",region_id:9},
{_id:52,name:"Mellila",region_id:19}