{_id:1,name:"Andalucía"},
{_id:2,name:"Aragón"},
{_id:3,name:"Principado de Asturias"},
{_id:4,name:"Illes Balears"},
{_id:5,name:"Cantabria"},
{_id:6,name:"Castilla y León"},
{_id:7,name:"Castilla-La Mancha"},
{_id:8,name:"Cataluña"},
{_id:9,name:"Ciudad de Ceuta"},
{_id:10,name:"Extremadura"},
{_id:11,name:"Galicia"},
{_id:12,name:"Canarias"},
{_id:13,name:"La Rioja"},
{_id:14,name:"Comunidad de Madrid"},
{_id:15,name:"Región de Murcia"},
{_id:16,name:"Comunidad Foral de Navarra"},
{_id:17,name:"País Vasco"},
{_id:18,name:"Comunitat Valenciana"},
{_id:19,name:"Ciudad de Melilla"}
