---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Copy my.cnf file
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
    owner: root
    group: root
    mode: 644
  notify: Restart mysql service

- name: Delete ddbb
  mysql_db:
    name: "{{ddbbname}}"
    state: absent

- name: Create ddbb
  mysql_db:
    name: "{{ddbbname}}"
    state: present

- name: Create ddbb user
  mysql_user:
    name: "{{ddbbuser}}"
    password: "{{ddbbpassword}}"
    priv: '*.*:ALL'
    state: present
    host: '%'
