---
provisioning:   ansible  # [puppet|ansible]
vb_name:        mikasaweb
vb_memory:      4096
vb_cpus:        2
box_name:       bento/ubuntu-16.04
#box_name:       centos/7
host_name:      mikasaweb.golili.net
locale_lc_all:  en_US.UTF-8
locale_lang:    en_US.UTF-8
roles_path:     ~/.ansible/roles
ports:
#- guestPort: 27017  #MongoDB
#  hostPort: 27017
- guestPort: 389    #OpenLDAP
  hostPort: 10389
