# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV["DEBIAN_FRONTEND"] = 'noninteractive'
#ENV["LC_ALL"] = settings['locale_lc_all']
#ENV["LANG"] = settings['locale_lang']
#ports = settings['ports']

Vagrant.configure(2) do |config|
  #config.vm.box = 'ubuntu/bionic64'
  config.vm.box = 'bento/ubuntu-20.04'
  config.vm.network "forwarded_port", host: 27017,guest: 27017  # MongoDB
  config.vm.network "forwarded_port", host: 10389,guest:   389  # OpenLDAP
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.network "private_network", ip: "10.0.2.16"

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'mikasaweb'
    vb.memory = 2048
    vb.cpus = 2
    #vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.gui = false
  end
  config.vm.hostname = 'mikasaweb.golili.net'
  #Needed to avoid 'Inappropriate ioctl for device' error message
  #config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "ansible" do |ansible|
    #ansible.inventory_path = 'environments/vagrant'
    ansible.compatibility_mode = '2.0'
    ansible.playbook = 'site.yml'
    ansible.galaxy_role_file = 'requirements.yml'
    ansible.galaxy_roles_path = '~/.ansible/roles'
  end

end
