CREATE TABLE COUNTRIES
(
	ID INTEGER NOT NULL PRIMARY KEY,
	CODE VARCHAR(5) NOT NULL,
	NAME VARCHAR(100)  NOT NULL
);

CREATE TABLE REGIONS
(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(30)
);

CREATE TABLE PROVINCES
(
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(150),
  REGION_ID INTEGER,
	FOREIGN KEY(REGION_ID) REFERENCES REGIONS(ID)
);

CREATE TABLE CITIES
(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	PROVINCE_ID INTEGER NOT NULL,
	FOREIGN KEY(PROVINCE_ID) REFERENCES PROVINCES(ID)
);


COMMIT;
