WHENEVER SQLERROR EXIT;
PROMPT Initializing ddbb creation;
PROMPT Creating tables...;

CREATE TABLE USERS
(
	USERNAME VARCHAR2(10) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(50) NOT NULL,
	SURNAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	ORGANIZATION VARCHAR2(100) NOT NULL,
	ENABLED INTEGER NOT NULL,
	CONSTRAINT CNT_ENABLED CHECK(ENABLED IN (1,0))
);

CREATE TABLE AUTHORITIES
(
	USERNAME VARCHAR2(10) NOT NULL,
	AUTHORITY VARCHAR2(10) NOT NULL,
	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME,AUTHORITY);

CREATE TABLE COUNTRIES
(
	ID INTEGER NOT NULL PRIMARY KEY,
	CODE VARCHAR(5) NOT NULL,
	NAME VARCHAR(100)  NOT NULL
);

CREATE TABLE REGIONS
(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(30)
);

CREATE TABLE PROVINCES
(
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(150),
  REGION_ID INTEGER,
	FOREIGN KEY(REGION_ID) REFERENCES REGIONS(ID)
);

CREATE TABLE CITIES
(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	PROVINCE_ID INTEGER NOT NULL,
	FOREIGN KEY(PROVINCE_ID) REFERENCES PROVINCES(ID)
);


COMMIT;
